version: "3.3"
services:
  db:
    image: postgres:9.6
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db

  backend:
    build: ./gatech-swapr-server-node
    user: "node"
    volumes:
      - ./gatech-swapr-server-node:/data/app
      - /data/node_modules
    working_dir: /data/app
    depends_on:
      - db
    networks:
      - backend
      - db

  www:
    image: nginx:latest
    depends_on:
      - backend
    networks:
      - backend
    volumes:
      - ./config/www/nginx.conf:/etc/nginx/conf.d/vhost.conf:ro
      - ./config/www/ssl:/etc/nginx/ssl:ro
      - ./gatech-swapr-client/dist:/usr/share/nginx/html:ro
    links:
      - backend

networks:
  backend:
  db:

volumes:
  db-data:
