version: "3.3"
services:
  test-db:
    image: postgres:9.6
    networks:
      - test-db
    environment:
      POSTGRES_USER: swapr
      POSTGRES_PASSWORD: changeme_devpasswd
      POSTGRES_DB: swapr_test

  test:
    build:
      context: ./gatech-swapr-server-node
      dockerfile: Dockerfile.test
    user: "node"
    tty: true
    working_dir: /data/app
    depends_on:
      - test-db
    networks:
      - test-db
    environment:
      PORT: 8001
      NODE_ENV: development
      DB_USERNAME: swapr
      DB_PASSWORD: changeme_devpasswd
      DB_NAME: swapr_test
    volumes:
      - ./config/backend/config.dev.json:/data/app/config/config.json:ro

networks:
  test-db: