---
# file: roles/dev_workstation/post_node_host/tasks/copy_ssh_keys.yml

# This is kind of skeezy, but I wasn't sure of what else to do. Copy the
# user's current SSH keys and hope for the best. This should cover git perms.
- name: copy private key
  copy: >
    src=~/.ssh/id_rsa
    dest="/home/{{ unprivved_app_user }}/.ssh/"
    owner="{{ unprivved_app_user }}"
    group="{{ unprivved_app_user }}"
    mode=0600

- name: copy public key
  copy: >
    src=~/.ssh/id_rsa.pub
    dest="/home/{{ unprivved_app_user }}/.ssh/"
    owner="{{ unprivved_app_user }}"
    group="{{ unprivved_app_user }}"
    mode=0644

- name: copy public key to authorized_keys
  copy: >
    src=~/.ssh/id_rsa.pub
    dest="/home/{{ unprivved_app_user }}/.ssh/authorized_keys"
    owner="{{ unprivved_app_user }}"
    group="{{ unprivved_app_user }}"
    mode=0644

- name: copy .gitconfig
  copy: >
    src=~/.gitconfig
    dest="/home/{{ unprivved_app_user }}/.gitconfig"
    owner="{{ unprivved_app_user }}"
    group="{{ unprivved_app_user }}"
    mode=0644
