---
# file: roles/dev_workstation/post_node_host/tasks/setup_samba.yml

- name: install samba
  apt: pkg={{ item }} state=installed
  with_items:
    - samba

- template: >
    src=etc/samba/smb.conf
    dest=/etc/samba/smb.conf
    owner=root group=root mode=0644
  notify: restart samba

- name: set the vagrant user's password to "vagrant"
  script: smbset.sh {{ unprivved_app_user }} vagrant
