# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 1.5.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "bento/ubuntu-16.10"

    config.vm.network :private_network, ip: "192.168.211.100"

    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
    end

    # This was causing sporadic vboxsf errors on some hosts with various
    # versions of VirtualBox and extensions on the guest. We'll just use
    # SFTP and avoid this nuisance.
    # config.vm.synced_folder ".", "/vagrant", :disabled => false

    config.vm.provision "ansible_local" do |ansible|
        #ansible.verbose = "vvvv"
        ansible.playbook = "developer.yml"
        # ansible.host_key_checking = false
        ansible.groups = {
          "developer" => ["default"],
        }
    end
end
