---
# file: roles/nginx/tasks/main.yml

- name: add nginx PPA
  apt_repository: repo='ppa:nginx/development'

- name: install nginx
  apt: pkg=nginx state=latest

- name: copy appserver vhost into place
  copy: >
    src=etc/nginx/sites-available/appserver
    dest=/etc/nginx/sites-available/appserver
    owner=root group=root mode=0644
  notify: restart nginx

- file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx

- file: >
    src=/etc/nginx/sites-available/appserver
    dest=/etc/nginx/sites-enabled/000-appserver
    owner=root group=root state=link
  notify: restart nginx

# The hooks above seem to be having a hard time actually restarting nginx.
# We'll do this 100% of the time in hopes of working around the issue.
- service: name=nginx state=restarted enabled=yes