---
# file: roles/node_host/tasks/setup_user.yml

- name: create web app user (non-development mode)
  user: >
    name="{{ unprivved_app_user }}"
    shell=/bin/bash
    generate_ssh_key=yes
    ssh_key_bits=2048
  when: not is_dev_env

- name: create web app user (development mode)
  user: >
    name="{{ unprivved_app_user }}"
    groups=sudo
    shell=/bin/bash
    generate_ssh_key=yes
    ssh_key_bits=2048
  when: is_dev_env

- copy: >
    src=host_keys/id_rsa dest=/home/{{ unprivved_app_user }}/.ssh/id_rsa
    owner="{{ unprivved_app_user }}"
    group="{{ unprivved_app_user }}"
    mode=0600

- copy: >
    src=host_keys/id_rsa.pub
    dest=/home/{{ unprivved_app_user }}/.ssh/id_rsa.pub
    owner="{{ unprivved_app_user }}"
    group="{{ unprivved_app_user }}"
    mode=0644

- copy: >
    src=host_keys/known_hosts
    dest=/home/{{ unprivved_app_user }}/.ssh/known_hosts
    owner="{{ unprivved_app_user }}"
    group="{{ unprivved_app_user }}"
    mode=0644

- copy: >
    src=host_keys/authorized_keys
    dest=/home/{{ unprivved_app_user }}/.ssh/authorized_keys
    owner="{{ unprivved_app_user }}"
    group="{{ unprivved_app_user }}"
    mode=0644

- template: >
    src=homedir/profile
    dest=/home/{{ unprivved_app_user }}/.profile
    owner="{{ unprivved_app_user }}"
    group="{{ unprivved_app_user }}"
    mode=0644
