---
# file: roles/node_host/tasks/setup_pyenv.yml

- name: Checking out SWAPR server, branch {{ git_repo_version }}
  git: >
    repo={{ git_repo }}
    dest={{ webapp_path }}
    update=no
    accept_hostkey=yes
    version={{ git_repo_version }}
  become: True
  become_user: "{{ unprivved_app_user }}"

- name: Checking out SWAPR client, branch {{ frontend_git_repo_version }}
  git: >
    repo={{ frontend_git_repo }}
    dest={{ frontend_path }}
    update=no
    accept_hostkey=yes
    version={{ git_repo_version }}
  become: True
  become_user: "{{ unprivved_app_user }}"

- name: set up git user.email
  command: git config --global user.email "{{ git_user_email }}" chdir="{{ webapp_path }}"
  become: yes
  become_user: "{{ unprivved_app_user }}"
  when: adjust_git_credentials is defined and adjust_git_credentials

- name: set up git user.name
  command: git config --global user.name "{{ git_user_name }}" chdir="{{ webapp_path }}"
  become: yes
  become_user: "{{ unprivved_app_user }}"
  when: adjust_git_credentials is defined and adjust_git_credentials

- name: build frontend environment (install npm dependencies)
  npm: >
    path={{ frontend_path }}

- name: build frontend environment (install bower)
  npm: >
    name=bower
    global=yes

- name: build frontend environment (install express)
  npm: >
    name=express
    global=yes

- name: build frontend environment (install bower dependencies)
  command: bower install
  become: yes
  become_user: "{{ unprivved_app_user }}"
  args:
    chdir: "{{ frontend_path }}"

- name: build frontend environment (install grunt-cli)
  npm: >
    name=grunt-cli
    global=yes

- name: build backend environement (install npm dependencies)
  npm: >
    path={{ webapp_path }}